CREATE TABLE IF NOT EXISTS `SECTORS` (
    `ID` CHAR(36) NOT NULL,
    `NAME` VARCHAR(100) NOT NULL UNIQUE,
    `ROOM` INT,
    `DESCRIPTION` VARCHAR(255) NOT NULL,
    `ANNEX_ID` CHAR(36) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (ANNEX_ID) REFERENCES ANNEXES(ID)
)