CREATE TABLE IF NOT EXISTS `SUBSECTORS` (
    `ID` CHAR(36) NOT NULL,
    `NAME` VARCHAR(100) NOT NULL UNIQUE,
    `ROOM` INT,
    `DESCRIPTION` VARCHAR(255) NOT NULL,
    `SECTOR_ID` CHAR(36) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (SECTOR_ID) REFERENCES SECTORS(ID)
)